version: "3.9"

services:
  app:
    build:
      context: .
    restart: always
    expose:
      - 8000
    volumes:
      - ./src:/src
    depends_on:
      - db
      - nginx

  db:
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=metallurgy_db
      - POSTGRES_USER=metallurgy_user
      - POSTGRES_PASSWORD=123@456
      - POSTGRES_PORT=5432

  nginx:
    build:
      context: ./nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./src/static
        target: /src/static

      - type: bind
        source: ./src/media
        target: /src/media

volumes:
  postgres_db: